<?php

$struct = array(
    0 =>
        array(
            0 => 'fullname',
            1 => 'first',
            2 => 'last',
            3 => 'address',
            4 => 'city',
            5 => 'st',
            6 => 'zip',
            7 => 'LO',
            8 => 'OWN-CARRIER CODE',
            9 => 'PURCHASE 1st MORTGAGE AMOUNT',
            10 => 'MOST RECENT MORTGAGE AMOUNT',
            11 => 'PURCHASE MORTGAGE DATE',
            12 => 'MOST RECENT MORTGAGE DATE',
            13 => 'PURCHASE 1ST MORTGAGE LOAN TYPE CODE',
            14 => 'MOST RECENT MORTGAGE LOAN TYPE CODE',
            15 => 'PURCHASE LENDER NAME',
            16 => 'MOST RECENT LENDER NAME',
            17 => 'PURCHASE 1ST MORTGAGE INTEREST RATE TYPE',
            18 => 'MOST RECENT MORTGAGE INTEREST RATE TYPE',
            19 => 'PURCHASE 1ST MORTGAGE INTEREST RATE',
            20 => 'MOST RECENT MORTGAGE INTEREST RATE',
            21 => 'EST HOME VALUE',
            22 => 'Loan to Value',
            23 => 'loan_officer',
        ),
    1 =>
        array(
            0 => 'MILES C BAKER',
            1 => 'MILES',
            2 => 'BAKER',
            3 => '901 ANDERSON ST ',
            4 => 'ANCHORAGE',
            5 => 'AK',
            6 => '99501',
            7 => 'Dean',
            8 => 'C006',
            9 => '443555',
            10 => '443555',
            11 => '20150102',
            12 => '20150102',
            13 => 'VA',
            14 => 'VA',
            15 => 'TITAN MTG CAP INC',
            16 => 'TITAN MTG CAP INC',
            17 => '',
            18 => '',
            19 => '0',
            20 => '0',
            21 => '485846',
            22 => '91',
        ),
    2 =>
        array(
            0 => 'DAVID L PETTY JR',
            1 => 'DAVID',
            2 => 'PETTY',
            3 => '928 DELANEY ST ',
            4 => 'ANCHORAGE',
            5 => 'AK',
            6 => '99501',
            7 => 'Dean',
            8 => 'C006',
            9 => '354375',
            10 => '354375',
            11 => '20150817',
            12 => '20150817',
            13 => 'VA',
            14 => 'VA',
            15 => 'FIRST NAT\'L BK/AK',
            16 => 'FIRST NAT\'L BK/AK',
            17 => '',
            18 => '',
            19 => '0',
            20 => '0',
            21 => '424318',
            22 => '84',
        ),
);