<!DOCTYPE html>
<html lang="en">

<head>
    <title>Redstone Mint</title>
    <style>
        body {
            font-family: sans-serif;
        }
    </style>
</head>

<body>

<div style="margin: auto; width: 80%;">
    <h1>
        <img src="https://redstonemail.com/companies/renderLogo/568ae6c2103fb4f64f2337d2" alt="logo" width="150px">
        Remove Encoded chars
    </h1>
    
    <p class="rsm-file-upload-info">
        <small>
            upload file
        </small>
    </p>
    
    <br>
    
    <form action="/redstone/tools/" method="POST" enctype="multipart/form-data">
        <div onclick="console.log('the click was picked up :)')">
            <input type="file" name="csv_file" data-flex="60" style="margin-right: 6px;">
        </div>
        <br><br>
        <input type="submit">
    </form>
    
    <br>
    
    <div id="rs-js-output" style="font-family: Consolas, sans-serif; font-size: 12px;">Output</div>
</div>

<script type="text/javascript">
    let outputElem = document.getElementById('rs-js-output');
    let applusCookie = getCookie('ApplusStatus');

    setInterval(function () {
        let applusCookie = getCookie('ApplusStatus');
        outputElem.innerHTML = "<h2>" + applusCookie + "</h2>";
    }, 2);

    function getCookie(cname) {
        let name = cname + "=";
        let ca = decodeURIComponent(document.cookie).split(';');
        for (let i = 0; i < ca.length; i++) {
            let c = ca[i];
            while (c.charAt(0) === ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) === 0) {
                return c.substring(name.length, c.length);
            }
        }

        return "";
    }
</script>

</body>
</html>