<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Redstone Print and Mail</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #9e2f00;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>


<body>

<h1>Redstone Print & Mail</h1>

<div class="rs-api-info">
    <p>Data tools Application Programming Interface</p>
</div>

<?php if(isset($name)) : ?>
    <h2>Ello <?= htmlspecialchars($name); ?>! ^_^/</h2>
<?php else: ?>
    <p><a href="/redstone/tools/encode-remove">Encode Remove</a></p>
<?php endif; ?>



</body>
</html>
