<?php
$info = 'Suppression List View wired up.';
?>

<!DOCTYPE html>
<html lang="en" data-ng-app="rsm-suppress">
<head>
    <meta charset="UTF-8">
    <title>Redstone Print and Mail</title>

    <link rel="stylesheet" href="./ui/vendor.css">
    <link rel="stylesheet" href="./ui/redstone.css">
</head>


<body>

<!-- The horizontal Navigation -->
<div data-ng-include="'ui/nav.horiz.html'"></div>

<section class="rsm-text-center">
    <h1>Suppression List</h1>
    <p><small><?= $info ?></small></p>
</section>

<br><br><br>

<p style="text-align: center;"> &copy; 2019 Redstone Print & Mail INC.</p>

<script src="./node_modules/modules.js"></script>

<script>
    let app = angular.module('rsm-suppress', [
        'ngAnimate', 'ngMaterial', 'ngMdIcons'
    ]);
</script>

</body>
</html>
