<?php

$appName = "ComAuto app";

$php_action = "?some=action";

?>

<!DOCTYPE html>

<html lang="en" data-ng-app="rsm-comauto-self-service">

<head>
    <title>Redstone Mint</title>
    <meta name="description" content="Data Engineering">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="author" content="Julius Alvarado">
    <style>
        body {
            font-family: sans-serif;
        }
        
        table {
            margin: auto;
        }
        
        .rsm-text-center {
            text-align: center;
        }
        
        .rsm-mt {
            margin-top: 10%;
        }
    </style>
</head>

<body data-ng-controller="EncodePresentCtrl">

<div style="margin: auto; width: 80%; padding-top: 10%">
    
    <form data-ng-submit="sf_toggleLoad()" name="rsmDownload" enctype="multipart/form-data"
          action="/redstone/tools/comauto-upload2/upload" method="POST">
        <input type="file" name="csv_file" data-flex="60" style="margin-right: 6px;">
        <br><br>
        <input type="submit">
    </form>
    
</div>


<!-- Node.js Modules -->
<script src="node_modules/modules.js"></script>
<!-- Custom JavaScript -->
<script src="comauto-upload/app.js"></script>


</body>
</html>


