<?php
$info = 'Suppression List View wired up.';
?>

<!DOCTYPE html>
<html lang="en" data-ng-app="rsm-suppress">
<head>
    <meta charset="UTF-8">
    <title>Redstone Print and Mail</title>

    <link rel="stylesheet" href="./ui/vendor.css">
    <link rel="stylesheet" href="./ui/redstone.css">
</head>

<body>

<!-- The horizontal Navigation -->
<div data-ng-include="'ui/nav.horiz.html'"></div>

<section id="rsm-suppression-list-controls">
    <div class="rsm-text-center">
        <h1>Suppression List</h1>
        <p><small><?= $info ?></small></p>
    </div>
    
    <div data-layout="row" data-layout-align="center start">
        <!-- left side  -->
        <div data-flex="40" data-flex-gt-md="30">
            <div data-layout="column" data-md-layout-align="center center"
                 data-layout-padding data-layout-margin>
                <!-- isset($php_action) ? $php_action : '' -->
                <h1>Choose the BASE file</h1>
                <form data-ng-submit="sf_toggleLoad()" name="rsmDownload" enctype="multipart/form-data"
                      action="/tools/app/<?= $php_action ?? '' ?>" method="POST">

                    <!-- the BASE csv file -->
                    <input type="file" name="base_file" data-flex="60" style="margin-right: 6px;">
                    
                    <br><br><br>

                    <h1>Choose suppression lists</h1>
                    <!-- 1-5 suppression lists... eventually 1-N -->
                    <input type="file" name="suppress[]" data-flex="60" style="margin-right: 6px;">
                    <br><br>
                    <input type="file" name="suppress[]" data-flex="60" style="margin-right: 6px;">
                    <br><br>
                    <input type="file" name="suppress[]" data-flex="60" style="margin-right: 6px;">
                    <br><br>
                    <input type="file" name="suppress[]" data-flex="60" style="margin-right: 6px;">
                    <br><br>
                    <input type="file" name="suppress[]" data-flex="60" style="margin-right: 6px;">
                    <br><br>

                    <md-button class="md-primary md-raised" type="submit">Submit</md-button>
                </form>
            </div>
        </div>

        <!-- right side  -->
        <div data-flex="50" data-flex-gt-md="60">
            <div data-layout="column" data-md-layout-align="center center"
                 data-layout-padding data-layout-margin>
                <h1>Future special conditions area</h1>
                <h4>Suppress record when [SOME_FIELD] contains [SOME_VALUES]</h4>
            </div>
        </div>
    </div>
</section>

<br><br><br>

<p style="text-align: center;"> &copy; 2019 Redstone Print & Mail INC.</p>

<script src="./node_modules/modules.js"></script>

<script>
    let app = angular.module('rsm-suppress', [
        'ngAnimate', 'ngMaterial', 'ngMdIcons'
    ]);
</script>

</body>
</html>
