<?php

$appName = "ComAuto app";

$php_action = "?some=action";

?>

<!DOCTYPE html>

<html lang="en" data-ng-app="rsm-comauto-self-service">

<head>
    <title>Redstone Mint</title>
    <meta name="description" content="Data Engineering">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="author" content="Julius Alvarado">
    <style>
        body {
            font-family: sans-serif;
        }
        
        table {
            margin: auto;
        }
        
        .rsm-text-center {
            text-align: center;
        }
        
        .rsm-mt {
            margin-top: 10%;
        }
        
        .flat-table {
            margin-bottom: 20px;
            border-collapse: collapse;
            font-family: 'Lato', Calibri, Arial, sans-serif;
            border: none;
            border-radius: 3px;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
        }
        
        .flat-table th, .flat-table td {
            box-shadow: inset 0 -1px rgba(0, 0, 0, 0.25),
            inset 0 1px rgba(0, 0, 0, 0.25);
        }
        
        .flat-table th {
            font-weight: normal;
            -webkit-font-smoothing: antialiased;
            padding: 1em;
            color: rgba(0, 0, 0, 0.45);
            text-shadow: 0 0 1px rgba(0, 0, 0, 0.1);
            font-size: 1.5em;
        }
        
        .flat-table td {
            color: #f7f7f7;
            padding: 0.7em 1em 0.7em 1.15em;
            text-shadow: 0 0 1px rgba(255, 255, 255, 0.1);
            font-size: 1.4em;
        }
        
        .flat-table tr {
            -webkit-transition: background 0.3s, box-shadow 0.3s;
            -moz-transition: background 0.3s, box-shadow 0.3s;
            transition: background 0.3s, box-shadow 0.3s;
        }
        
        .flat-table-1 {
            background: #336ca6;
        }
        
        .flat-table-1 tr:hover {
            background: rgba(0, 0, 0, 0.19);
        }
        
        .flat-table-2 tr:hover {
            background: rgba(0, 0, 0, 0.1);
        }
        
        .flat-table-2 {
            background: #f06060;
        }
        
        .flat-table-3 {
            background: #52be7f;
        }
        
        .flat-table-3 tr:hover {
            background: rgba(0, 0, 0, 0.1);
        }
    </style>
</head>


<body data-ng-controller="EncodePresentCtrl">

<div style="margin: auto; width: 80%;">
    <h2 class="rsm-title-bar">
        <img src="http://192.168.7.17/img/rs-sm.png"
             alt="logo" width="120px">
        <span style="position: relative; top: -20px"><?= $appName ?></span>
    </h2>
    <h4>status: {{s_status}}</h4>
    
    <br>
    
    <form data-ng-submit="sf_toggleLoad()" name="rsmDownload" enctype="multipart/form-data"
          action="/redstone/tools/comauto-upload2/upload" method="POST">
        <input type="file" name="csv_file" data-flex="60" style="margin-right: 6px;">
        <br><br>
        <input type="submit">
    </form>
    
    <br>
    
</div>

<div class="rsm-text-center">
    <h4>Upload CSV to compute <br>Job Costing and Commission</h4>
    <p class="rsm-encode-check">
        <small>When the program completes a zipped folder will get downloaded.</small>
    </p>
</div>

<footer class="rsm-text-center rsm-mt">
    <h5>Redstone Automation v0.0.{{8-9+2}}</h5>
</footer>

<!-- Node.js Modules -->
<script src="node_modules/modules.js"></script>
<!-- Custom JavaScript -->
<script src="comauto-upload/app.js"></script>

</body>
</html>


